# Generated by Django 4.2.4 on 2024-04-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("ActivityID", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("duration", models.IntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("DestinationID", models.IntegerField()),
            ],
            options={
                "db_table": "Activity",
            },
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "DestinationID",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Destination",
            },
        ),
        migrations.CreateModel(
            name="TripOptions",
            fields=[
                ("OptionID", models.IntegerField(primary_key=True, serialize=False)),
                ("DestinationID", models.IntegerField()),
                ("NumberOfDays", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "TripOptions",
            },
        ),
        migrations.CreateModel(
            name="TripOptionsActivity",
            fields=[
                (
                    "optionactivityid",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "activity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recco.activity"
                    ),
                ),
                (
                    "optionid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recco.tripoptions",
                    ),
                ),
            ],
            options={
                "db_table": "TripOptionsActivity",
            },
        ),
    ]
