# Generated by Django 4.2.4 on 2024-04-04 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recco", "0002_accommodation_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="DestinationID",
            field=models.ForeignKey(
                db_column="DestinationID",
                on_delete=django.db.models.deletion.CASCADE,
                to="recco.destination",
            ),
        ),
    ]
