# Generated by Django 4.2.4 on 2024-04-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recco", "0003_alter_activity_destinationid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodation",
            name="DestinationID",
            field=models.ForeignKey(
                db_column="DestinationID",
                on_delete=django.db.models.deletion.CASCADE,
                to="recco.destination",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="AccommodationID",
            field=models.ForeignKey(
                blank=True,
                db_column="AccommodationID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recco.accommodation",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="ActivityID",
            field=models.ForeignKey(
                blank=True,
                db_column="ActivityID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recco.activity",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="DestinationID",
            field=models.ForeignKey(
                db_column="DestinationID",
                on_delete=django.db.models.deletion.CASCADE,
                to="recco.destination",
            ),
        ),
    ]
