# Generated by Django 5.0.3 on 2024-04-08 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recco", "0005_alter_accommodation_accommodationid_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
